export type DecantSize = { ml: number; price: number };

export type Product = {
  id: string;
  name: string;
  house: string;
  line: "Arabian" | "Designer" | "Niche";
  gender: "Him" | "Her" | "Unisex";
  notes: string[];
  occasions: string[];
  seasons: string[];
  bestSeller?: boolean;
  sizes: DecantSize[];
};

export const LINES = ["All", "Arabian", "Designer", "Niche"] as const;
export type Line = (typeof LINES)[number];

export const GENDERS = ["All", "Him", "Her", "Unisex"] as const;
export type Gender = (typeof GENDERS)[number];

// ──────────────────────────────────────────────────────────────────────────
// CATALOG
// ──────────────────────────────────────────────────────────────────────────
export const products: Product[] = [

  // ── ARABIAN LINE ────────────────────────────────────────────────────────
  {
    id: "khamrah",
    name: "Khamrah",
    house: "Lattafa",
    line: "Arabian",
    gender: "Unisex",
    notes: ["Amber", "Vanilla", "Myrrh", "Cinnamon", "Tonka Bean", "Praline"],
    occasions: ["Night", "Date"],
    seasons: ["Fall", "Winter"],
    bestSeller: true,
    sizes: [{ ml: 3, price: 28 }, { ml: 5, price: 42 }, { ml: 10, price: 72 }, { ml: 15, price: 95 }],
  },
  {
    id: "khamrah-qahwa",
    name: "Khamrah Qahwa",
    house: "Lattafa",
    line: "Arabian",
    gender: "Unisex",
    notes: ["Coffee", "Cardamom", "Vanilla", "Cinnamon", "Praline", "Musk"],
    occasions: ["Night"],
    seasons: ["Fall", "Winter"],
    bestSeller: true,
    sizes: [{ ml: 3, price: 28 }, { ml: 5, price: 42 }, { ml: 10, price: 72 }, { ml: 15, price: 95 }],
  },
  {
    id: "angham",
    name: "Angham",
    house: "Lattafa",
    line: "Arabian",
    gender: "Unisex",
    notes: ["Rose", "Saffron", "Jasmine", "Amber", "Musk", "Pink Pepper", "Ylang Ylang"],
    occasions: ["Day", "Evening", "Signature"],
    seasons: ["Spring", "Summer", "Fall", "Winter"],
    bestSeller: true,
    sizes: [{ ml: 3, price: 28 }, { ml: 5, price: 42 }, { ml: 10, price: 72 }, { ml: 15, price: 95 }],
  },
  {
    id: "supremacy-collectors",
    name: "Supremacy Collectors Edition",
    house: "Afnan",
    line: "Arabian",
    gender: "Him",
    notes: ["Oud", "Rose", "Amber", "Cinnamon", "Vanilla", "Patchouli", "Bergamot"],
    occasions: ["Evening", "Formal", "Signature"],
    seasons: ["Fall", "Winter"],
    bestSeller: true,
    sizes: [{ ml: 3, price: 32 }, { ml: 5, price: 50 }, { ml: 10, price: 85 }, { ml: 15, price: 115 }],
  },
  {
    id: "hawas",
    name: "Hawas",
    house: "Rasasi",
    line: "Arabian",
    gender: "Him",
    notes: ["Aquatic", "Bergamot", "Ambergris", "Cinnamon", "Musk", "Orange Blossom"],
    occasions: ["Day"],
    seasons: ["Spring", "Summer"],
    bestSeller: true,
    sizes: [{ ml: 3, price: 25 }, { ml: 5, price: 38 }, { ml: 10, price: 65 }, { ml: 15, price: 85 }],
  },
  {
    id: "hawas-fire",
    name: "Hawas Fire",
    house: "Rasasi",
    line: "Arabian",
    gender: "Him",
    notes: ["Ambergris", "Aquatic", "Clary Sage", "Egyptian Jasmine"],
    occasions: ["Day", "Evening", "Signature"],
    seasons: ["Spring", "Summer", "Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 30 }, { ml: 5, price: 45 }, { ml: 10, price: 78 }, { ml: 15, price: 105 }],
  },
  {
    id: "9pm",
    name: "9PM",
    house: "Afnan",
    line: "Arabian",
    gender: "Him",
    notes: ["Amber", "Vanilla", "Patchouli", "Bergamot", "Musk"],
    occasions: ["Evening", "Night"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 25 }, { ml: 5, price: 38 }, { ml: 10, price: 65 }, { ml: 15, price: 85 }],
  },
  {
    id: "9pm-elixir",
    name: "9PM Elixir",
    house: "Afnan",
    line: "Arabian",
    gender: "Him",
    notes: ["Amber", "Sandalwood", "Tonka Bean", "Bergamot", "Musk"],
    occasions: ["Evening", "Formal"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 30 }, { ml: 5, price: 45 }, { ml: 10, price: 78 }, { ml: 15, price: 105 }],
  },
  {
    id: "ajayeb-dubai",
    name: "Ajayeb Dubai",
    house: "Lattafa",
    line: "Arabian",
    gender: "Unisex",
    notes: ["Musk", "Vanilla", "Amber", "Woods", "Bergamot"],
    occasions: ["Casual", "Signature"],
    seasons: ["Spring", "Fall"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 25 }, { ml: 5, price: 38 }, { ml: 10, price: 65 }, { ml: 15, price: 85 }],
  },
  {
    id: "adonis-oud",
    name: "Adonis Oud",
    house: "Rayhaan",
    line: "Arabian",
    gender: "Him",
    notes: ["Oud", "Rose", "Musk", "Sandalwood", "Amber"],
    occasions: ["Evening", "Signature"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 25 }, { ml: 5, price: 38 }, { ml: 10, price: 65 }, { ml: 15, price: 85 }],
  },
  {
    id: "ajayeb-dubai-portrait",
    name: "Ajayeb Dubai Portrait",
    house: "Lattafa",
    line: "Arabian",
    gender: "Her",
    notes: ["Floral", "Amber", "Musk", "Vanilla", "Bergamot"],
    occasions: ["Day", "Signature"],
    seasons: ["Spring", "Summer"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 22 }, { ml: 5, price: 34 }, { ml: 10, price: 58 }, { ml: 15, price: 78 }],
  },
  {
    id: "al-nashama-caprice",
    name: "Al Nashama Caprice",
    house: "Lattafa",
    line: "Arabian",
    gender: "Her",
    notes: ["Floral", "Musk", "Sandalwood", "Bergamot", "Rose"],
    occasions: ["Day", "Evening"],
    seasons: ["Spring", "Summer"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 25 }, { ml: 5, price: 38 }, { ml: 10, price: 65 }, { ml: 15, price: 85 }],
  },

  // ── DESIGNER LINE ───────────────────────────────────────────────────────
  {
    id: "sauvage-edp",
    name: "Sauvage Eau de Parfum",
    house: "Dior",
    line: "Designer",
    gender: "Him",
    notes: ["Ambroxan", "Bergamot", "Lavender", "Nutmeg", "Star Anise", "Vanilla"],
    occasions: ["Day", "Night"],
    seasons: ["Spring", "Summer", "Fall", "Winter"],
    bestSeller: true,
    sizes: [{ ml: 3, price: 55 }, { ml: 5, price: 85 }, { ml: 10, price: 150 }, { ml: 15, price: 200 }],
  },
  {
    id: "bleu-de-chanel-edp",
    name: "Bleu de Chanel EDP",
    house: "Chanel",
    line: "Designer",
    gender: "Him",
    notes: ["Cedar", "Jasmine", "Sandalwood", "Vetiver", "Ginger", "Patchouli"],
    occasions: ["Formal", "Day", "Evening", "Signature"],
    seasons: ["Spring", "Summer", "Fall", "Winter"],
    bestSeller: true,
    sizes: [{ ml: 3, price: 60 }, { ml: 5, price: 92 }, { ml: 10, price: 165 }, { ml: 15, price: 225 }],
  },
  {
    id: "y-edp",
    name: "Y Eau de Parfum",
    house: "Yves Saint Laurent",
    line: "Designer",
    gender: "Him",
    notes: ["Apple", "Bergamot", "Amberwood", "Sage", "Vetiver", "Tonka Bean"],
    occasions: ["Formal", "Office", "Romantic", "Signature"],
    seasons: ["Spring", "Summer", "Fall"],
    bestSeller: true,
    sizes: [{ ml: 3, price: 50 }, { ml: 5, price: 78 }, { ml: 10, price: 140 }, { ml: 15, price: 188 }],
  },
  {
    id: "cdni-edp",
    name: "Club de Nuit Intense Man EDP",
    house: "Armaf",
    line: "Designer",
    gender: "Him",
    notes: ["Pineapple", "Apple", "Bergamot", "Rose", "Jasmine", "Musk", "Vanilla"],
    occasions: ["Casual", "Evening", "Night", "Signature"],
    seasons: ["Spring", "Summer", "Fall"],
    bestSeller: true,
    sizes: [{ ml: 3, price: 35 }, { ml: 5, price: 55 }, { ml: 10, price: 96 }, { ml: 15, price: 130 }],
  },
  {
    id: "acqua-di-gio-parfum",
    name: "Acqua Di Gio Parfum",
    house: "Giorgio Armani",
    line: "Designer",
    gender: "Him",
    notes: ["Aquatic", "Incense", "Bergamot", "Cypress", "Mineral"],
    occasions: ["Casual", "Day"],
    seasons: ["Spring", "Summer"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 52 }, { ml: 5, price: 80 }, { ml: 10, price: 143 }, { ml: 15, price: 192 }],
  },
  {
    id: "acqua-di-gio-profondo",
    name: "Acqua Di Gio Profondo",
    house: "Giorgio Armani",
    line: "Designer",
    gender: "Him",
    notes: ["Aquatic", "Bergamot", "Green Mandarin", "Musk", "Mineral"],
    occasions: ["Casual", "Day"],
    seasons: ["Spring", "Summer"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 52 }, { ml: 5, price: 80 }, { ml: 10, price: 143 }, { ml: 15, price: 192 }],
  },
  {
    id: "1-million-edp",
    name: "1 Million EDP",
    house: "Paco Rabanne",
    line: "Designer",
    gender: "Him",
    notes: ["Grapefruit", "Cinnamon", "Leather", "Amber", "Rose"],
    occasions: ["Evening", "Night", "Signature"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 48 }, { ml: 5, price: 74 }, { ml: 10, price: 132 }, { ml: 15, price: 178 }],
  },
  {
    id: "eros-edp",
    name: "Eros Eau de Parfum",
    house: "Versace",
    line: "Designer",
    gender: "Him",
    notes: ["Mint", "Vanilla", "Tonka Bean", "Apple", "Amber"],
    occasions: ["Evening", "Romantic"],
    seasons: ["Fall", "Winter", "Spring"],
    bestSeller: true,
    sizes: [{ ml: 3, price: 48 }, { ml: 5, price: 74 }, { ml: 10, price: 132 }, { ml: 15, price: 178 }],
  },
  {
    id: "212-vip-black",
    name: "212 VIP Black",
    house: "Carolina Herrera",
    line: "Designer",
    gender: "Him",
    notes: ["Tonka Bean", "Vanilla", "Amber Accord", "Musk"],
    occasions: ["Night", "Date", "Signature"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 40 }, { ml: 5, price: 62 }, { ml: 10, price: 110 }, { ml: 15, price: 148 }],
  },
  {
    id: "alien-goddess",
    name: "Alien Goddess",
    house: "Mugler",
    line: "Designer",
    gender: "Her",
    notes: ["Jasmine", "Vanilla", "Sandalwood", "Cashmeran"],
    occasions: ["Evening", "Night"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 48 }, { ml: 5, price: 74 }, { ml: 10, price: 130 }, { ml: 15, price: 175 }],
  },
  {
    id: "addict-edp",
    name: "Addict Eau de Parfum",
    house: "Dior",
    line: "Designer",
    gender: "Her",
    notes: ["Vanilla", "Rose", "Sandalwood", "Benzyl Benzoate"],
    occasions: ["Evening", "Signature"],
    seasons: ["Fall", "Winter", "Spring"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 55 }, { ml: 5, price: 85 }, { ml: 10, price: 150 }, { ml: 15, price: 200 }],
  },

  // ── NICHE LINE ──────────────────────────────────────────────────────────
  {
    id: "724-mfk",
    name: "724",
    house: "Maison Francis Kurkdjian",
    line: "Niche",
    gender: "Unisex",
    notes: ["Green Tea", "Cedar", "White Musk", "Amber"],
    occasions: ["Day", "Signature"],
    seasons: ["Spring", "Summer"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 120 }, { ml: 5, price: 188 }, { ml: 10, price: 340 }, { ml: 15, price: 460 }],
  },
  {
    id: "african-leather",
    name: "African Leather",
    house: "Memo Paris",
    line: "Niche",
    gender: "Unisex",
    notes: ["Leather", "Rose", "Sandalwood", "Incense", "Oud"],
    occasions: ["Evening", "Formal", "Signature"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 110 }, { ml: 5, price: 172 }, { ml: 10, price: 310 }, { ml: 15, price: 420 }],
  },
  {
    id: "a-la-nuit",
    name: "A La Nuit",
    house: "Serge Lutens",
    line: "Niche",
    gender: "Her",
    notes: ["Jasmine", "Rose", "Musk", "White Floral"],
    occasions: ["Evening", "Night"],
    seasons: ["Summer", "Spring"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 95 }, { ml: 5, price: 148 }, { ml: 10, price: 268 }, { ml: 15, price: 360 }],
  },
  {
    id: "acqua-viva",
    name: "Acqua Viva",
    house: "Profumum Roma",
    line: "Niche",
    gender: "Unisex",
    notes: ["Aquatic", "Iris", "Ambergris", "Musk", "Citrus"],
    occasions: ["Day"],
    seasons: ["Spring", "Summer"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 90 }, { ml: 5, price: 140 }, { ml: 10, price: 252 }, { ml: 15, price: 340 }],
  },
  {
    id: "akaster",
    name: "Akaster",
    house: "Parfums de Marly",
    line: "Niche",
    gender: "Him",
    notes: ["Amber", "Vanilla", "Tonka Bean", "Cinnamon", "Elemi"],
    occasions: ["Evening", "Formal"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 98 }, { ml: 5, price: 155 }, { ml: 10, price: 280 }, { ml: 15, price: 378 }],
  },
  {
    id: "a-men",
    name: "A*Men",
    house: "Mugler",
    line: "Niche",
    gender: "Him",
    notes: ["Coffee", "Caramel", "Patchouli", "Vanilla", "Sandalwood"],
    occasions: ["Evening", "Night"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 80 }, { ml: 5, price: 125 }, { ml: 10, price: 225 }, { ml: 15, price: 305 }],
  },
];
