export type DecantSize = { ml: number; price: number };

export type Product = {
  id: string;
  name: string;
  house: string;
  line: "Arabian" | "Designer" | "Niche";
  gender: "Him" | "Her" | "Unisex";
  notes: string[];
  occasions: string[];
  seasons: string[];
  bestSeller?: boolean;
  sizes: DecantSize[];
};

export const LINES = ["All", "Arabian", "Designer", "Niche"] as const;
export type Line = (typeof LINES)[number];

export const GENDERS = ["All", "Him", "Her", "Unisex"] as const;
export type Gender = (typeof GENDERS)[number];

// ──────────────────────────────────────────────────────────────────────────
// CATALOG
// ──────────────────────────────────────────────────────────────────────────
export const products: Product[] = [

  // ── ARABIAN LINE ────────────────────────────────────────────────────────
  {
    id: "khamrah",
    name: "Khamrah",
    house: "Lattafa",
    line: "Arabian",
    gender: "Unisex",
    notes: ["Amber", "Vanilla", "Myrrh", "Cinnamon", "Tonka Bean", "Praline"],
    occasions: ["Night", "Date"],
    seasons: ["Fall", "Winter"],
    bestSeller: true,
    sizes: [{ ml: 5, price: 315 }, { ml: 9, price: 511 }, { ml: 15, price: 768 }],
  },
  {
    id: "khamrah-qahwa",
    name: "Khamrah Qahwa",
    house: "Lattafa",
    line: "Arabian",
    gender: "Unisex",
    notes: ["Coffee", "Cardamom", "Vanilla", "Cinnamon", "Praline", "Musk"],
    occasions: ["Night"],
    seasons: ["Fall", "Winter"],
    bestSeller: true,
    sizes: [{ ml: 5, price: 339 }, { ml: 9, price: 549 }, { ml: 15, price: 828 }],
  },
  {
    id: "angham",
    name: "Angham",
    house: "Lattafa",
    line: "Arabian",
    gender: "Unisex",
    notes: ["Rose", "Saffron", "Jasmine", "Amber", "Musk", "Pink Pepper", "Ylang Ylang"],
    occasions: ["Day", "Evening", "Signature"],
    seasons: ["Spring", "Summer", "Fall", "Winter"],
    bestSeller: true,
    sizes: [{ ml: 5, price: 319 }, { ml: 9, price: 517 }, { ml: 15, price: 778 }],
  },
  {
    id: "supremacy-collectors",
    name: "Supremacy Collectors Edition",
    house: "Afnan",
    line: "Arabian",
    gender: "Him",
    notes: ["Oud", "Rose", "Amber", "Cinnamon", "Vanilla", "Patchouli", "Bergamot"],
    occasions: ["Evening", "Formal", "Signature"],
    seasons: ["Fall", "Winter"],
    bestSeller: true,
    sizes: [{ ml: 5, price: 496 }, { ml: 9, price: 837 }, { ml: 15, price: 1273 }],
  },
  {
    id: "hawas",
    name: "Hawas",
    house: "Rasasi",
    line: "Arabian",
    gender: "Him",
    notes: ["Aquatic", "Bergamot", "Ambergris", "Cinnamon", "Musk", "Orange Blossom"],
    occasions: ["Day"],
    seasons: ["Spring", "Summer"],
    bestSeller: true,
    sizes: [{ ml: 5, price: 340 }, { ml: 9, price: 560 }, { ml: 15, price: 837 }],
  },
  {
    id: "hawas-fire",
    name: "Hawas Fire",
    house: "Rasasi",
    line: "Arabian",
    gender: "Him",
    notes: ["Ambergris", "Aquatic", "Clary Sage", "Egyptian Jasmine"],
    occasions: ["Day", "Evening", "Signature"],
    seasons: ["Spring", "Summer", "Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 5, price: 430 }, { ml: 9, price: 710 }, { ml: 15, price: 1072 }],
  },
  {
    id: "9pm",
    name: "9PM",
    house: "Afnan",
    line: "Arabian",
    gender: "Him",
    notes: ["Amber", "Vanilla", "Patchouli", "Bergamot", "Musk"],
    occasions: ["Evening", "Night"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 5, price: 361 }, { ml: 9, price: 594 }, { ml: 15, price: 897 }],
  },
  {
    id: "9pm-elixir",
    name: "9PM Elixir",
    house: "Afnan",
    line: "Arabian",
    gender: "Him",
    notes: ["Amber", "Sandalwood", "Tonka Bean", "Bergamot", "Musk"],
    occasions: ["Evening", "Formal"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 5, price: 461 }, { ml: 9, price: 773 }, { ml: 15, price: 1174 }],
  },
  {
    id: "ajayeb-dubai",
    name: "Ajayeb Dubai",
    house: "Lattafa",
    line: "Arabian",
    gender: "Unisex",
    notes: ["Musk", "Vanilla", "Amber", "Woods", "Bergamot"],
    occasions: ["Casual", "Signature"],
    seasons: ["Spring", "Fall"],
    bestSeller: false,
    sizes: [{ ml: 5, price: 354 }, { ml: 9, price: 581 }, { ml: 15, price: 877 }],
  },
  {
    id: "adonis-oud",
    name: "Adonis Oud",
    house: "Rayhaan",
    line: "Arabian",
    gender: "Him",
    notes: ["Oud", "Rose", "Musk", "Sandalwood", "Amber"],
    occasions: ["Evening", "Signature"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 5, price: 319 }, { ml: 9, price: 517 }, { ml: 15, price: 778 }],
  },
  {
    id: "ajayeb-dubai-portrait",
    name: "Ajayeb Dubai Portrait",
    house: "Lattafa",
    line: "Arabian",
    gender: "Her",
    notes: ["Floral", "Amber", "Musk", "Vanilla", "Bergamot"],
    occasions: ["Day", "Signature"],
    seasons: ["Spring", "Summer"],
    bestSeller: false,
    sizes: [{ ml: 5, price: 283 }, { ml: 9, price: 453 }, { ml: 15, price: 679 }],
  },
  {
    id: "al-nashama-caprice",
    name: "Al Nashama Caprice",
    house: "Lattafa",
    line: "Arabian",
    gender: "Her",
    notes: ["Floral", "Musk", "Sandalwood", "Bergamot", "Rose"],
    occasions: ["Day", "Evening"],
    seasons: ["Spring", "Summer"],
    bestSeller: false,
    sizes: [{ ml: 5, price: 354 }, { ml: 9, price: 581 }, { ml: 15, price: 877 }],
  },

  // ── DESIGNER LINE ───────────────────────────────────────────────────────
  {
    id: "sauvage-edp",
    name: "Sauvage Eau de Parfum",
    house: "Dior",
    line: "Designer",
    gender: "Him",
    notes: ["Ambroxan", "Bergamot", "Lavender", "Nutmeg", "Star Anise", "Vanilla"],
    occasions: ["Day", "Night"],
    seasons: ["Spring", "Summer", "Fall", "Winter"],
    bestSeller: true,
    sizes: [{ ml: 3, price: 853 }, { ml: 5, price: 1384 }, { ml: 9, price: 2434 }, { ml: 15, price: 3748 }],
  },
  {
    id: "bleu-de-chanel-edp",
    name: "Bleu de Chanel EDP",
    house: "Chanel",
    line: "Designer",
    gender: "Him",
    notes: ["Cedar", "Jasmine", "Sandalwood", "Vetiver", "Ginger", "Patchouli"],
    occasions: ["Formal", "Day", "Evening", "Signature"],
    seasons: ["Spring", "Summer", "Fall", "Winter"],
    bestSeller: true,
    sizes: [{ ml: 3, price: 999 }, { ml: 5, price: 1632 }, { ml: 9, price: 2882 }],
  },
  {
    id: "y-edp",
    name: "Y Eau de Parfum",
    house: "Yves Saint Laurent",
    line: "Designer",
    gender: "Him",
    notes: ["Apple", "Bergamot", "Amberwood", "Sage", "Vetiver", "Tonka Bean"],
    occasions: ["Formal", "Office", "Romantic", "Signature"],
    seasons: ["Spring", "Summer", "Fall"],
    bestSeller: true,
    sizes: [{ ml: 3, price: 542 }, { ml: 5, price: 865 }, { ml: 9, price: 1501 }, { ml: 15, price: 2303 }],
  },
  {
    id: "cdni-edp",
    name: "Club de Nuit Intense Man EDP",
    house: "Armaf",
    line: "Designer",
    gender: "Him",
    notes: ["Pineapple", "Apple", "Bergamot", "Rose", "Jasmine", "Musk", "Vanilla"],
    occasions: ["Casual", "Evening", "Night", "Signature"],
    seasons: ["Spring", "Summer", "Fall"],
    bestSeller: true,
    sizes: [{ ml: 5, price: 425 }, { ml: 9, price: 700 }, { ml: 15, price: 1075 }],
  },
  {
    id: "acqua-di-gio-parfum",
    name: "Acqua Di Gio Parfum",
    house: "Giorgio Armani",
    line: "Designer",
    gender: "Him",
    notes: ["Aquatic", "Incense", "Bergamot", "Cypress", "Mineral"],
    occasions: ["Casual", "Day"],
    seasons: ["Spring", "Summer"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 632 }, { ml: 5, price: 1014 }, { ml: 9, price: 1770 }, { ml: 15, price: 2718 }],
  },
  {
    id: "acqua-di-gio-profondo",
    name: "Acqua Di Gio Profondo",
    house: "Giorgio Armani",
    line: "Designer",
    gender: "Him",
    notes: ["Aquatic", "Bergamot", "Green Mandarin", "Musk", "Mineral"],
    occasions: ["Casual", "Day"],
    seasons: ["Spring", "Summer"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 593 }, { ml: 5, price: 950 }, { ml: 9, price: 1655 }, { ml: 15, price: 2540 }],
  },
  {
    id: "1-million-edp",
    name: "1 Million Parfum",
    house: "Paco Rabanne",
    line: "Designer",
    gender: "Him",
    notes: ["Grapefruit", "Cinnamon", "Leather", "Amber", "Rose"],
    occasions: ["Evening", "Night", "Signature"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 470 }, { ml: 5, price: 745 }, { ml: 9, price: 1284 }, { ml: 15, price: 1966 }],
  },
  {
    id: "eros-edp",
    name: "Eros Eau de Parfum",
    house: "Versace",
    line: "Designer",
    gender: "Him",
    notes: ["Mint", "Vanilla", "Tonka Bean", "Apple", "Amber"],
    occasions: ["Evening", "Romantic"],
    seasons: ["Fall", "Winter", "Spring"],
    bestSeller: true,
    sizes: [{ ml: 3, price: 331 }, { ml: 5, price: 514 }, { ml: 9, price: 869 }, { ml: 15, price: 1323 }],
  },
  {
    id: "212-vip-black",
    name: "212 VIP Black",
    house: "Carolina Herrera",
    line: "Designer",
    gender: "Him",
    notes: ["Tonka Bean", "Vanilla", "Amber Accord", "Musk"],
    occasions: ["Night", "Date", "Signature"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 385 }, { ml: 5, price: 603 }, { ml: 9, price: 1029 }, { ml: 15, price: 1570 }],
  },
  {
    id: "alien-goddess",
    name: "Alien Goddess",
    house: "Mugler",
    line: "Designer",
    gender: "Her",
    notes: ["Jasmine", "Vanilla", "Sandalwood", "Cashmeran"],
    occasions: ["Evening", "Night"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 609 }, { ml: 5, price: 979 }, { ml: 9, price: 1706 }, { ml: 15, price: 2615 }],
  },
  {
    id: "addict-edp",
    name: "Addict Eau de Parfum",
    house: "Dior",
    line: "Designer",
    gender: "Her",
    notes: ["Vanilla", "Rose", "Sandalwood", "Benzyl Benzoate"],
    occasions: ["Evening", "Signature"],
    seasons: ["Fall", "Winter", "Spring"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 853 }, { ml: 5, price: 1384 }, { ml: 9, price: 2434 }],
  },

  // ── NICHE LINE ──────────────────────────────────────────────────────────
  {
    id: "724-mfk",
    name: "724",
    house: "Maison Francis Kurkdjian",
    line: "Niche",
    gender: "Unisex",
    notes: ["Green Tea", "Cedar", "White Musk", "Amber"],
    occasions: ["Day", "Signature"],
    seasons: ["Spring", "Summer"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 1404 }, { ml: 5, price: 2301 }, { ml: 9, price: 4087 }, { ml: 15, price: 6308 }],
  },
  {
    id: "african-leather",
    name: "African Leather",
    house: "Memo Paris",
    line: "Niche",
    gender: "Unisex",
    notes: ["Leather", "Rose", "Sandalwood", "Incense", "Oud"],
    occasions: ["Evening", "Formal", "Signature"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 768 }, { ml: 5, price: 1242 }, { ml: 9, price: 2179 }, { ml: 15, price: 3352 }],
  },
  {
    id: "a-la-nuit",
    name: "A La Nuit",
    house: "Serge Lutens",
    line: "Niche",
    gender: "Her",
    notes: ["Jasmine", "Rose", "Musk", "White Floral"],
    occasions: ["Evening", "Night"],
    seasons: ["Summer", "Spring"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 1173 }, { ml: 5, price: 1916 }, { ml: 9, price: 3393 }],
  },
  {
    id: "acqua-viva",
    name: "Acqua Viva",
    house: "Profumum Roma",
    line: "Niche",
    gender: "Unisex",
    notes: ["Aquatic", "Iris", "Ambergris", "Musk", "Citrus"],
    occasions: ["Day"],
    seasons: ["Spring", "Summer"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 1024 }, { ml: 5, price: 1668 }, { ml: 9, price: 2946 }, { ml: 15, price: 4540 }],
  },
  {
    id: "akaster",
    name: "Akaster (Batch 2017)",
    house: "Parfums de Marly",
    line: "Niche",
    gender: "Him",
    notes: ["Amber", "Vanilla", "Tonka Bean", "Cinnamon", "Elemi"],
    occasions: ["Evening", "Formal"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 603 }, { ml: 5, price: 967 }, { ml: 9, price: 1685 }, { ml: 15, price: 2588 }],
  },
  {
    id: "a-men",
    name: "A*Men",
    house: "Mugler",
    line: "Niche",
    gender: "Him",
    notes: ["Coffee", "Caramel", "Patchouli", "Vanilla", "Sandalwood"],
    occasions: ["Evening", "Night"],
    seasons: ["Fall", "Winter"],
    bestSeller: false,
    sizes: [{ ml: 3, price: 448 }, { ml: 5, price: 709 }, { ml: 9, price: 1200 }, { ml: 15, price: 1860 }],
  },
];
